### ISSUE TITLE
Typescript typings are incomplete / not a module

### ISSUE THREAD

**Issue by phiresky** [rhashimoto/wa-sqlite#14]
You can't import the main api via

import * as SQLite from "wa-sqlite";

because it throws this error:

File '.../node_modules/wa-sqlite/src/types/sqlite-api.d.ts' is not a module.

The dist file etc are also not typed, `import SQLiteAsyncESMFactory from "wa-sqlite/dist/wa-sqlite-async.mjs";` throws a type error, as does `import * as VFS from "wa-sqlite/src/VFS";`

**Comment by rhashimoto** [comment]
Hmm. I don't write in Typescript. I added the declaration file because it was the easiest way to generate documentation and provide VSCode Intellisense hints (for Javascript).

It looks like you can at least compile by using a local Javascript file to import from the package and then import _that_ Javascript into Typescript. But that's horrible because all the API signatures are lost.

I haven't found great Typescript documentation for what I'm trying to do so I haven't figured out how to fix this, but I'll keep poking at it.

**Comment by rhashimoto** [comment]
@phiresky I checked in an attempt at a fix. Can you please give it a try? It appears to work on the attached micro-project.

[wa-sqlite-ts-bug.zip](https://github.com/rhashimoto/wa-sqlite/files/6488317/wa-sqlite-ts-bug.zip)

**Comment by rhashimoto** [comment]
Reopening because it's fixed for the dist/ and API files but not other files like src/VFS.js. Need to check examples/ as well.
