### ISSUE TITLE
Trigger on multiple tabs 

### ISSUE THREAD

**Issue by linhttbk97** [rhashimoto/wa-sqlite#140]
I'm attempting to utilize the demo, and it works fine on a single tab. I'm trying to create a trigger that fires upon insertion. However, in the case of multiple tabs, the trigger only fires on the tab where the insert operation is executed. I'm aware that I could use a SharedWorker to share the database connection across tabs. But in my case, I need to support many version of browser like safari 15 ( that doesn't support Sharedworker)

**Comment by sgbeal** [comment]
You might (just speculating) be able to use [storage events for that purpose](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event). You could set aside a specific localStorage or sessionStorage key for that purpose, set it to some arbitrary value when you make a change, and react to that event in your other tabs. Someone in the sqlite forum suggested that idea for cross-tab notification of changes.

**Comment by tantaman** [comment]
another option is the broadcast channel api. I'd expect this to be quicker than storage events since you don't need to write anything. https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API

I've hooked up the https://www.sqlite.org/c3ref/update_hook.html to fire events through a broadcast channel so all tabs can respond to changes made by other tabs. Note that exposing the update hook in wa_sqlite requires https://github.com/rhashimoto/wa-sqlite/pull/133

**Comment by rhashimoto** [comment]
> You might (just speculating) be able to use [storage events for that purpose](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event).

That can work, and might be the best choice before Safari 15.4 which OP might need here, but in general [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel) is a better signaling mechanism (as I previously mentioned [here](https://sqlite.org/forum/info/86cd553cc02666ae)). It is delivered to all origin contexts, i.e. not just Window, can be precisely targeted (storage fires on every localStorage or sessionStorage change, potentially causing irrelevant callbacks), and can deliver any structured cloneable payload.

[Ninja-ed by @tantaman but I'll post anyway]
