### ISSUE TITLE
blobs should be uint8array not int8array?

### ISSUE THREAD

**Issue by tantaman** [rhashimoto/wa-sqlite#65]
I notice that blobs, when read out of wa-sqlite, are being returned as `int8array` rather than `uint8array`.

Also when inserting blobs -- you expect `int8array`.

I believe these should be `Uint8Array`s instead.

**Comment by rhashimoto** [comment]
Yes, this was a mistake. Uint8Array would have been better. I haven't changed it because it would be a breaking change and I haven't come up with a strong enough argument to overcome that. Converting to Uint8Array is easy and they are blobs so they are typically not useful directly as bytes anyway.

**Comment by tantaman** [comment]
Makes sense. I went ahead and fixed the issue in a fork (https://github.com/vlcn-io/wa-sqlite/commit/e2faeaebdc0f1fc11398324c9fb3f1c43493064c) if you ever decide to tackle it yourself.

Maybe I'll revert to converting in the client in order not to maintain a fork.

Love the work on the project by the way. I was using the official SQLite WASM build for a bit but being unable to use it from multiple tabs was a deal breaker so I came back to wa-sqlite. It also looks possible to run wa-sqlite in a SharedWorker which isn't possible for the official sqlite build.

On the tabs front -- the OPFS locks are currently pretty coarse grained and make the official wasm build unusable from many tabs. More context here: https://sqlite.org/forum/forumpost/58a377083cd24a29

**Comment by rhashimoto** [comment]
If I accumulate enough other reasons to break the API then I'll likely toss in this change.

I've never used SharedWorker for anything so I can't say for sure that wa-sqlite and all the example VFS classes work in one, but I can't think of any reason why it wouldn't.

I don't think I've seen the OPFS issue from the forum post with my own OPFS code. I haven't looked specifically at OPFS in multiple tabs, but I do have a contention test that verifies atomic transactions across 8 workers. My OPFS and IndexedDB VFS classes use the WebLocks API for locking, so they block there and not on the storage-level locks...which one would think should actually be slower. So I think there may be hope that this is a SQLite WASM bug that could be fixed by the SQLite folks at some point.

One idea I have for you is to try the patched VFS (the one that you reported was slow but didn't throw) without using a journal file (e.g. with `PRAGMA journal_mode=OFF;`). That might tell someone whether the slowness is related to the journal (which isn't `xLock`-ed).

**Comment by rhashimoto** [comment]
Now changed in a [branch](https://github.com/rhashimoto/wa-sqlite/tree/breaking-changes) with other [breaking changes](https://github.com/rhashimoto/wa-sqlite/discussions/76).

**Comment by rhashimoto** [comment]
Merged.
